---
title: "shearston_plots"
author: "J Shearston"
date: "November 19, 2018"
output: github_document
---

```{r setup, include=FALSE}

library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))

```


## Graph of variation in proportion of fastball vs off-speed pitches and temperature


```{r temp and prop ff}

# Create proportion of ff to all pitch dataset

propff_db = pitch_tidy_db %>% 
  mutate(ff = str_detect(pitch_type, "FF")) %>% 
  group_by(y, m, d, tmax) %>% 
  summarise(n = n(),
            ff_sum = sum(ff, na.rm = TRUE),
            prop_ff = (ff_sum/n)*100) %>% 
  mutate(prop_ff = round(prop_ff, digits = 1))

# tmax and proportion of ff  

propff_db %>%
  filter(prop_ff != 0) %>% 
  ggplot(aes(x = prop_ff, y = tmax)) +
  geom_point() +
  geom_smooth() +
  labs(
    title = "Proportion of Thrown Pitches that are Fastballs and Max Temperature",
    x = "Proportion of Pitches that are Fastballs",
    y = "Max Temperature (C)"
  )


```


## Graph of speed of fastballs and temperature


```{r temp & pitch speed (fastball only)}

## HEADS UP -- each graph takes 2-6 minutes to run and view

# tmax and pitch speed, fastball only, facet by inning

complete_db %>% 
  filter(pitch_type == "FF") %>% 
  ggplot(aes(x = start_speed, y = tmax)) +
  geom_point() +
  facet_wrap(~inning)

# tmax and pitch speed, fastball only, facet by team

pitch_tidy_db %>% 
  filter(pitch_type == "FF") %>% 
  ggplot(aes(x = tmax, y = start_speed)) +
  geom_point() +
  facet_wrap(~team_name) +
  labs(
    title = "Fastball Pitch Speed and Max Temperature, by Home Team",
    x = "Max Temperature (C)",
    y = "Pitch Starting Speed (MPH)"
  )

# tmax and pitch speed, fastball only, facet by outcome (homerun, strikeout, etc)

pitch_tidy_db %>% 
  filter(pitch_type == "FF") %>% 
  ggplot(aes(x = tmax, y = start_speed)) +
  geom_point() +
  facet_wrap(~event) +
  labs(
    title = "Fastball Pitch Speed and Max Temperature, by Pitch Outcome",
    x = "Max Temperature (C)",
    y = "Pitch Starting Speed (MPH)"
  )

# tmax and pitch speed, fastball only, facet by ball/strike/foul

complete_db %>% 
  filter(pitch_type == "FF") %>% 
  ggplot(aes(x = start_speed, y = tmax)) +
  geom_point() +
  facet_wrap(~type)

```


## Exploratory -- graphs of temp and pitch speed (all pitch types)


```{r temp & pitch speed (all pitch type)}

## HEADS UP -- each graph takes 2-6 minutes to run and view

# tmax and pitch speed, facet by pitch type

complete_db %>% 
  filter(y == "2016") %>% 
  ggplot(aes(x = start_speed, y = tmax)) +
  geom_point() +
  facet_wrap(~pitch_type)

# add pitch outcome = Home Run or Strikeout (as color)

complete_db %>% 
  filter(y == "2016", event == "Home Run" | event == "Strikeout") %>% 
  mutate(event_f = as.factor(event)) %>% 
  ggplot(aes(x = start_speed, y = tmax, color = event_f)) +
  geom_point() +
  facet_wrap(~pitch_type) +
  theme(legend.position = "bottom")

# add team name (as color)

complete_db %>% 
  filter(y == "2016") %>% 
  mutate(team_name_f = as.factor(team_name)) %>% 
  ggplot(aes(x = start_speed, y = tmax, color = team_name_f)) +
  geom_point() +
  facet_wrap(~pitch_type) +
  theme(legend.position = "bottom")

# facet by team name (color = pitch type)

complete_db %>% 
  filter(y == "2016") %>% 
  mutate(team_name_f = as.factor(team_name)) %>% 
  ggplot(aes(x = start_speed, y = tmax, color = pitch_type)) +
  geom_point() +
  facet_wrap(~team_name_f) +
  theme(legend.position = "bottom")


```


## Further Analysis - stadium specific


```{r Texas Rangers stadium}

#games at Texas Rangers stadium

pitch_tidy_db %>% 
  filter(pitch_type == "FF" & team_name == "Texas Rangers") %>% 
  ggplot(aes(x = tmax, y = start_speed, color = pitcher_name)) +
  geom_point() +
  facet_wrap(~inning_side) +
  labs(
    title = "Fastball Pitch Speed and Max Temperature at Texas Rangers Stadium",
    x = "Max Temperature (C)",
    y = "Pitch Starting Speed (MPH)"
  ) +
  theme(legend.position = "none")

#restrict to sept

pitch_tidy_db %>% 
  filter(pitch_type == "FF" & team_name == "Texas Rangers" & m == "09") %>% 
  ggplot(aes(x = tmax, y = start_speed)) +
  geom_point(aes(color = pitcher_name)) +
  geom_smooth(method = 'lm', color = "black") +
  geom_smooth() +
  facet_wrap(~inning_side) +
  labs(
    title = "Fastball Pitch Speed and Max Temperature at Texas Rangers Stadium",
    x = "Max Temperature (C)",
    y = "Pitch Starting Speed (MPH)"
  ) +
  theme(legend.position = "none")

#restrict to oct

pitch_tidy_db %>% 
  filter(pitch_type == "FF" & team_name == "Texas Rangers" & m == "10") %>% 
  ggplot(aes(x = tmax, y = start_speed, color = pitcher_name)) +
  geom_point() +
  facet_wrap(~inning_side) +
  labs(
    title = "Fastball Pitch Speed and Max Temperature at Texas Rangers Stadium",
    x = "Max Temperature (C)",
    y = "Pitch Starting Speed (MPH)"
  ) +
  theme(legend.position = "none")

```


```{r Red Sox stadium}

#games at Boston Red Sox stadium

pitch_tidy_db %>% 
  filter(pitch_type == "FF" & team_name == "Boston Red Sox") %>% 
  ggplot(aes(x = tmax, y = start_speed, color = pitcher_name)) +
  geom_point() +
  facet_wrap(~inning_side) +
  labs(
    title = "Fastball Pitch Speed and Max Temperature at Boston Red Sox Stadium",
    x = "Max Temperature (C)",
    y = "Pitch Starting Speed (MPH)"
  ) +
  theme(legend.position = "none")

#restrict to sept

pitch_tidy_db %>% 
  filter(pitch_type == "FF" & team_name == "Boston Red Sox" & m == "09") %>% 
  ggplot(aes(x = tmax, y = start_speed)) +
  geom_point(aes(color = pitcher_name)) +
  geom_smooth(method = 'lm', color = "black") +
  geom_smooth() +
  facet_wrap(~inning_side) +
  labs(
    title = "Fastball Pitch Speed and Max Temperature at Boston Red Sox Stadium",
    x = "Max Temperature (C)",
    y = "Pitch Starting Speed (MPH)"
  ) +
  theme(legend.position = "none")

#restrict to oct

pitch_tidy_db %>% 
  filter(pitch_type == "FF" & team_name == "Boston Red Sox" & m == "10") %>% 
  ggplot(aes(x = tmax, y = start_speed, color = pitcher_name)) +
  geom_point() +
  facet_wrap(~inning_side) +
  labs(
    title = "Fastball Pitch Speed and Max Temperature at Boston Red Sox Stadium",
    x = "Max Temperature (C)",
    y = "Pitch Starting Speed (MPH)"
  ) +
  theme(legend.position = "none")

```


## Further Analysis - create final graph

```{r}

# Texas Rangers Stadium in September

tr9 = pitch_tidy_db %>% 
  filter(pitch_type == "FF" & team_name == "Texas Rangers" & m == "09") %>% 
  ggplot(aes(x = tmax, y = start_speed)) +
  geom_point(aes(color = pitcher_name)) +
  geom_smooth(method = 'lm', color = "black") +
  geom_smooth() +
  facet_wrap(~inning_side) +
  labs(
    title = "Fastball Pitch Speed and Max Temperature at Texas Rangers Stadium", subtitle = "Pitchers = Colors, Month = September",
    x = "Max Temperature (C)",
    y = "Pitch Starting Speed (MPH)"
  ) +
  theme(legend.position = "none")

# Boston Red Sox Stadium in September

brs9 = pitch_tidy_db %>% 
  filter(pitch_type == "FF" & team_name == "Boston Red Sox" & m == "09") %>% 
  ggplot(aes(x = tmax, y = start_speed)) +
  geom_point(aes(color = pitcher_name)) +
  geom_smooth(method = 'lm', color = "black") +
  geom_smooth() +
  facet_wrap(~inning_side) +
  labs(
    title = "Fastball Pitch Speed and Max Temperature at Boston Red Sox Stadium", subtitle = "Pitchers = Colors, Month = September",
    x = "Max Temperature (C)",
    y = "Pitch Starting Speed (MPH)"
  ) +
  theme(legend.position = "none")

#Join Graphs

library(patchwork)
tr9 + brs9

```

